version: '3'

services: 
    web:
        container_name: myfirstcompose
        image: nginx:latest
        ports:
            - 80:80
        volumes:
            - ./www:/usr/share/nginx/html
    php:
        container_name: myfistphpcompose
        image: php:7.2-apache
        depends_on:
            - web
        ports:
            - 88:80
        volumes: 
            - web:/var/www/html
    bd:
        container_name: myfirstDB
        image: mysql
        command: --default-authentication-plugin=mysql_native_password
        environment:
            MYSQL_ROOT_PASSWORD: test1234
            MYSQL_USER: usrtest
            MYSQL_DATABASE: test_db
        ports: 
            - 6000:3306
volumes: 
    web: