name: testingDockerImage

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: docker test
      run: |
        docker -v
        docker ps -a
        docker run dtorres9/fifiglet:20200723 figlet hola mundo
