# This is a basic workflow to help you get started with Actions

name: testingDockerImage
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]


jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: docker test
      run: |
        docker -v
        docker ps -a
